//import com.google.common.collect.ImmutableMap;
//import com.sun.glass.events.KeyEvent;
//import io.appium.java_client.android.AndroidDriver;
//import io.appium.java_client.android.AndroidKeyCode;
//import io.appium.java_client.android.AndroidKeyMetastate;
//import io.appium.java_client.android.ListensToLogcatMessages;
//import io.appium.java_client.android.nativekey.AndroidKey;
//import org.openqa.selenium.By;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.testng.Assert;
//import org.testng.IAlterTestName;
//import org.testng.TestNG;
//import org.testng.annotations.Parameters;
//import org.testng.annotations.Test;
//import sun.plugin2.message.GetAppletMessage;
//import utils.*;
//
//import java.io.IOException;
//import java.util.Arrays;
//import java.util.List;
//import java.util.Map;
//
//import static io.appium.java_client.android.AndroidKeyCode.KEYCODE_DPAD_UP;
//import static io.appium.java_client.android.AndroidKeyCode.KEYCODE_MENU;
//import static io.appium.java_client.android.nativekey.AndroidKey.MOVE_HOME;
//
//public class startover extends BaseTest {
//    public startover() throws IOException {
//    } //Enter channel x and then watch 15 min then start over 15 min, exit start over, move to another channel and so on
//    @Parameters({"deviceName"})
//    @Test(description = "start over",priority = 1,alwaysRun=true)
//    public void startOver(String deviceName) throws InterruptedException, IOException {
//        capabilities.setCapability("deviceName", deviceName);
////        Log.info("--- ממתין עד שפרטנר טי וי תעלה --- ");
////        WebDriverWait wait = new WebDriverWait(driver, 20);
////        wait.until(ExpectedConditions.visibilityOfElementLocated((By.id("exo_content_frame"))));
//        String activity = driver.currentActivity();
//        Boolean act = activity.equals("com.ifeelsmart.common.IFSNativeActivityImpl");
//        while (act) {
//            activity = driver.currentActivity();
//            act = activity.equals("com.ifeelsmart.common.IFSNativeActivityImpl");
//            Thread.sleep(20000);
//            Log.info("Moving to Channel 11");
//            driver.pressKeyCode(8);
//            driver.pressKeyCode(8);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("DOWN");
//            driver.pressKeyCode(20);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("Back");
//            driver.pressKeyCode(4);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(2000);
//            Log.info("Moving to Channel 50");
//            driver.pressKeyCode(12);
//            driver.pressKeyCode(7);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("DOWN");
//            driver.pressKeyCode(20);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("Back");
//            driver.pressKeyCode(4);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(2000);
//            Log.info("Moving to Channel 51");
//            driver.pressKeyCode(12);
//            driver.pressKeyCode(8);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("DOWN");
//            driver.pressKeyCode(20);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("Back");
//            driver.pressKeyCode(4);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(2000);
//            Log.info("Moving to Channel 52");
//            driver.pressKeyCode(12);
//            driver.pressKeyCode(9);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("DOWN");
//            driver.pressKeyCode(20);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("Back");
//            driver.pressKeyCode(4);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(2000);
//            Log.info("Moving to Channel 60");
//            driver.pressKeyCode(13);
//            driver.pressKeyCode(7);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("DOWN");
//            driver.pressKeyCode(20);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(1000);
//            Log.info("15 min");
//            Thread.sleep(900000);
//            Log.info("Back");
//            driver.pressKeyCode(4);
//            Thread.sleep(1000);
//            Log.info("OK");
//            driver.pressKeyCode(23);
//            Thread.sleep(2000);
//        }
//       Log.info("Crashed ...");
//    }}